.circleci/config.yml
.yamllint.yml

feat(ci): added yamllint check

---

middlewares/login.js
test/api/authorization.test.js

pretty much self-explanatory, wonder how I've forgotten to do it from start. also wrote tests for it.
This also fixes MyAEGEE + Wiki integration, as the first letter is capitalized somehow in email.

fix(login): allow case-insensitive login

---

middlewares/fetch.js

returning bodies' shadow circles on `/bodies/:id`

fix(bodies): populate body shadow circles. Partially fixes HELP-1160

---

middlewares/members.js
test/api/users-mail-change.test.js

if the user requests to change their email, they can create a MailChange object with the new_email set to something that some user in the DB already has, and later when confirming email change it cannot update the user because the new email is something that other person has already, now it's not the case as the user cannot even trigger the email change to something that is not unique and is presented already.
\+ tests for this.

fix(users): checking email uniqueness before creating MailChange. Fixes MEMB-864

---

.circleci/config.yml
lib/constants.js
lib/helpers.js

rationale in the ticket: https://myaegee.atlassian.net/browse/MEMB-855

fix(general): concat fields for searching. Fixes MEMB-855

---

migrations/20200720134741-add-task-description-body.js
models/Body.js

Backend support for https://github.com/AEGEE/frontend/pull/488

feat: add task description bodies

---

middlewares/bodies.js
test/api/bodies-listing.test.js

feat(bodies): allow returning deleted bodies

---

migrations/20200810161400-add-privacy-consent.js
models/User.js

Backend for issue [MA-48](https://myaegee.atlassian.net/browse/MA-48)

feat(users): add privacy consent field

---

lib/server.js
middlewares/members.js
test/api/users-deleting.test.js

backend for https://myaegee.atlassian.net/browse/MA-100, there will be another PR for frontend

feat(users): allow deleting users. Fixes MA-100

---

lib/constants.js

Add constants, so that endpoints still function when updating the privacy consent.
This was forgotten to be added in #88

chore(constants): update constants for storing privacy consent

---

.github/workflows/codeql-analysis.yml

On network it did not show much yet since it's a small repo, so I'm using this as a second test
On network it generated this; https://github.com/AEGEE/network/security/code-scanning

chore(codeql-analysis): add codeql analysis

---

.github/workflows/codeql-analysis.yml

I copied too much from network, the main branch is master here

chore(codeql-analysis): fixed branch name

---

models/User.js
test/unit/users.test.js

Backend version of https://github.com/AEGEE/frontend/pull/700

fix(email): disallow specific email domains

---

lib/constants.js
migrations/20201125220434-add-abbreviation-to-bodies.js
models/Body.js

Can be used to store abbreviations for bodies like JC/CD/CEWG/ITC etc.
In the frontend I will add validation so this is not for locals.
This can also be used to generate Google groups for the body

feat(body): add abbreviation

---

models/User.js
test/api/campaigns-submission.test.js

Frontend still need to be fixed and database needs to be cleaned of these people

fix(user): not allow numerical usernames. Partially fixes MA-176

---

middlewares/members.js

Needs to be merged with https://github.com/AEGEE/summeruniversity/pull/25

fix(members): add notification_email to getUser change

---

lib/morgan.js
middlewares/login.js

Related to https://github.com/AEGEE/discounts/pull/254

fix(mail): added notification_email to morgan

---

migrations/20210314211126-add-postal-address-bodies.js
models/Body.js

Implements [MA-181](https://myaegee.atlassian.net/browse/MA-181?atlOrigin=eyJpIjoiZjY4ZTliMTMyYWIxNGQ5MDk1OTFlZmEyMzFlYmEzNjkiLCJwIjoiaiJ9)

feat(body): add postal address bodies

---

models/Body.js
test/unit/bodies.test.js

Why would you need a phone and address for bodies like NetCom and Les Anciens?

fix(body): update mandatory fields body

---

lib/server.js
middlewares/members.js
models/User.js
scripts/seed.js
test/api/users-superadmin.test.js

Useful for local development, not meant to be used on prod

fix(superadmin): add endpoint for superadmin

---

test/api/users-superadmin.test.js

I was not using the latest master when making the previous PR so the tests did not account for the change in createAccessToken

chore(superadmin): fix tests

---

.circleci/config.yml
docker/core/Dockerfile
package.json
scripts/seed.js

So CI recreates the database, including the seeder. So if this succeeds the seeder is correct.

ci(database): add check for recreating db

---

models/Body.js
package.json
scripts/seed.js
test/api/bodies-listing.test.js
test/scripts/generator.js
test/unit/bodies.test.js
test/unit/unique-indexes.test.js

Forced Body Code to be 3 letters long.
Furthermore in the attached issue https://myaegee.atlassian.net/browse/MA-202.
For the FrontEnd part, the PR is: https://github.com/AEGEE/frontend/pull/1254

fix(body): validate body code to be 3 letters
