middlewares/my-permissions.js
test/api/my-permissions-my-circles.test.js

okay, so let's start doing things through PR properly :D
so there's POST /my_permissions endpoint, which accepts the body as JSON with action and object, and returns a list of circles where I have this permission (local one). and it's used in both events and statutory services to get the list of circles (and therefore bodies), where I have this permission.
how it works: it takes the local:action:object permission, then queries all CirclePermissions for this permission, then recursively gets the list of all the direct and indirect circles for this permission (like, if the General Board circle has this permission, then Board AEGEE-Moskva, inherited from it, also has it).
then it queries for all circles, where I am a member (I've missed this part) from this circles list and returns it to the …

fix(permissions): fix POST /my_permissions endpoint

---

lib/logger.js

we do not log field if it's exactly the one of the fields in the stop list, but we don't if it includes it. for example, `password` is hidden, but `password_copy` isn't
this makes it a little bit more broad by filtering not only fields that are named exactly the same as in config, but also if it contains one of the fields in the config.

fix(logging): hide more sensitive stuff

---

middlewares/members.js

fixed 1) template name for email change and 2) email title (both were a mistype).
I'm also working on frontend so will do a few things here as well later.

fix(members): fix template and mail title for email change

---

lib/server.js
middlewares/body-memberships.js
middlewares/circle-memberships.js
middlewares/login.js
test/api/body-memberships-details.test.js
test/api/circle-memberships-details.test.js
test/api/logout.test.js

Added 3 endpoints that were presented in the old core, but are missing in a new core.
1) GET /bodies/:id/members - returns a single body memberships
2) GET /bodies/:id/members - returns a single circle memberships
3) POST /logout - invalidates a refresh token, effectively logging out user (the access token doesn't need to be invalidated, as it only is valid for 10 minutes). This is different that in the new core (you provide the access token and I've no idea how it was working there), I'll make a PR for the frontend changes. 
\+ added tests for this stuff so we'd have 100% coverage as usual.

Add missing endpoints

---

models/Permission.js
models/User.js
test/unit/users.test.js

1) if `date_of_birth is not provided, the validation fails, which shouldn't be as the field is nullable
2) when updating the permission, the `combined` field wasn't updated, it is updated now.
\+ wrote a test for 1)

fix(models): small fixes

---

middlewares/members.js
test/api/users-primary-body.test.js

now you can update your primary body not only if you have update:member permission, but also if you're trying to change your own primary body, which is how it should've worked before.
also fixed a test which was incorrect.

fix(users): allow changing primary body. Fixes HELP-1222

---

models/User.js
test/unit/users.test.js

converting `''` to `null` before saving user, otherwise it complains about "Invalid date"

fix(users): allow saving users with date_of_birth as empty string. Fixes HELP-1258

---

middlewares/bodies.js
test/api/body-members-creating.test.js

Fixes 4.2 of https://myaegee.atlassian.net/browse/HELP-1264
there's a limited set of fields that is updated in the db, and the mail_confirmed_at wasn't there, so I've passed it. also wrote a test that fails without my change and passes now.

fix(members): save mail_confirmed_at when registering user in body. Fixes HELP-1264

---

models/BodyMembership.js

probably fixes https://myaegee.atlassian.net/browse/HELP-1265, not sure about that
my theory is: the user is created within the transaction and the circle membership isn't, so it tries to create a circle membership for not existing user, not sure if it's true or not but at least it shouldn't break anything.

fix(members): forward transaction when creating user

---

middlewares/bodies.js

apparently Model.destroy() expects a transaction as a property of the first argument, not second.
this was causing a timeout of a request when trying to delete a body, I assume this should (in theory) fix the core not responding after deleting a body.

fix(bodies): passing transaction correctly when deleting a body

---

config/index.js
lib/logger.js
lib/morgan.js

I want to understand who/which service is actually doing that much requests to `/members/me` while being unauthorized.
Future to-do things:
- add a `x-service` header (or sth like this) to all requests done from other MyAEGEE services, to identify which service they are going to
- probably reject those requests without this header in the future
This should help us figuring out the logging a bit.

feat(logs): log request headers

---

lib/server.js
middlewares/members.js
scripts/seed.js
test/api/users-confirmation.test.js
test/api/users-unconfirmed-listing.test.js

a) added 2 endpoints: 
1) /members/unconfirmed - list unconfirmed users
2) /members/:id/confirm - confirm users
b) added permissions for seeding
c) added tests

feat(general): allow listing and confirming users manually. Fixes MA-77

---

docker/docker-compose.yml

Apparently you need to do extra stuff when upgrading postgres versions, per https://www.postgresql.org/docs/current/pgupgrade.html
Postgres 10 will get updates until November 2022 so there is no hurry in updating

chore(postgres): put postgres back to 10

---

lib/constants.js
migrations/20201025145040-add-gsuiteID-to-users.js
migrations/20201027145040-add-gsuiteID-to-circles.js
migrations/20201125200123-add-gsuiteID-to-bodies.js
models/Body.js
models/Circle.js
models/User.js

NB this is merged into #183 
some things are to check obviously as I am not aware of their correctness

fix(gsuite): add gsuite model

---

middlewares/login.js

So they can use their username, their email and their gsuite_id

fix(login): allow people to login with gsuite_id

---

lib/constants.js
middlewares/campaigns.js
middlewares/join-requests.js
middlewares/login.js
migrations/20201114150900-add-primary-email-users.js
models/User.js
test/scripts/generator.js
test/unit/users.test.js

Add backend for [#722](https://github.com/AEGEE/frontend/pull/722), fixes issue [MA-134](https://myaegee.atlassian.net/browse/MA-134)

fix(user): allow users to choose notification email. Fixes MA-134

---

middlewares/members.js
test/api/users-details.test.js

Members now have the global:view_members:body permission to add organizers from other locals, with this change we also store the correct information when storing the event

fix(members): change getUser for event creation

---

middlewares/members.js
test/api/users-confirmation.test.js

When you manually confirm a user, the MailConfirmation object is still present. This would trigger the cron job and in 2 days the manually confirmed user would still be deleted. This fixes that.

fix(user): delete confirmation with manual

---

lib/server.js
middlewares/members.js
test/api/users-email.test.js
test/api/users-searching.test.js

Frontend and other modules will be updated later as well, but nothing will break since only new endpoints are added. searchAllUsers will be used for adding members to a body and other places where you want to add people but don't need all the additional data of that user, currently it all requires view:member for that. getUsersEmail is for the massmailer so with one request we get all current emails.

feat(members): add endpoints for searching and retrieving email

---

.circleci/config.yml

https://github.com/AEGEE/core/pull/379 requires a version of Node >14.17 and 16.13 is the current LTS. Will update the other images here later with the updates done in discounts (when I've updated the Slack messages as well since I prefer the old ones)

ci(dbap): update docker image for semantic-release update

---

models/AccessToken.js
models/Body.js
test/unit/bodies.test.js

Remove default: '' for values, which must not be empty.
Emails must not be empty.  CLE, MHW, ZRH have no emails.

fix(bodies): replace SHOULD with MUST for mandatory requirements

---

docker/core/Dockerfile

It seems that the sha tag is actually for Node 20.2.0

chore(docker): update Node
